### PR TITLE
Client-side and Web Server Authentication

### PR DESCRIPTION
**Pull request by jad-b**
Fails at not having a valid User account setup in the database,  but otherwise appears to be checking out. 
- Client's authenticate using the `client.TorqueAPI` object
- Using HTTP's `BasicAuth` header - no password hashing/encryption yet, still plain-text.
- API server is recognizing the bad request and writing an error back

**To Test**

``` bash
# Start up the DB so we can successfully connect
docker-compose -f deploy/docker-compose.yml
# Compile the webserver's binary into your $GOPATH/bin and run the server
make install && torque_rest
# Run the Redteam acceptance test
TEST_ARGS="-run TestAuthentication" make redteam
# You should see a Response printed with "Invalid Credentials" in your test output. That's good!
```

### CODE REVIEW

**Comment by jad-b** [comment]
@moogar0880 I think this is good to go. Next step is to finish the User database CRUD operations, as well as some setup/teardown for testing.

**Comment by moogar0880** [comment]
haven't looked through all of the changes yet and I'm hitting this error trying to run the tests... thoughts?

```
$ TEST_ARGS="-run TestAuthentication" make redteam                                                                        
go test -v github.com/jad-b/torque/redteam -run TestAuthentication
=== RUN   TestAuthentication
--- FAIL: TestAuthentication (0.00s)
    authenticate_test.go:36: Authenticating against  http://localhost:18000
    authenticate_test.go:39: No response received from authentication request
FAIL
exit status 1
FAIL    github.com/jad-b/torque/redteam 0.139s
make: *** [redteam] Error 1

```

**Comment by jad-b** [comment]
Very weird - have you double checked the import paths closely? You could
also try by specifying the files directly, but I read the go tools are
intended to work with package names.

**Comment by jad-b** [comment]
Closing; included by #14

**Pull request closed without merging**
