### PR TITLE
Adding initial user implementation

### PR DESCRIPTION
**Pull request by moogar0880**
We should definitely sync up on our approach to auth (sesions and whatnot).

Also, wasn't entirely sure what you were going for the the `HTTP*` methods for the RestfulClient interface, so I left those empty for now. We should probably talk about that as well

### CODE REVIEW

**Comment by jad-b** [comment]
The RESTfulClient methods have that HTTP\*  prefix because Delete is shared by database CRUD and HTTP methods. I've gone back and forth and how to name these things.

**Comment by moogar0880** [comment]
But what piece of logic are they supposed to encompass? It looks like in your `bodyweight` package it does something with a url? and then returns json? I'm assuming those are something that the CLI uses, but I'm not 100% sure

**Comment by jad-b** [comment]
So, another question is do we have User field in structs to model foreign keys, or do we keep them separate? Right now I'm leaning towards fields.

**Comment by jad-b** [comment]
Re: what does RESTfulClient do? It's the web API for the client library. Interacting with torque objects as a client over the internet. Right now the only user is the CLI, but it'll eventually be something all clients use. Accessing the DB via the CLI is something that will only be for personal torque servers and us debugging things.

**Pull request merged**
